apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: lovetest-auto-discover
  namespace: argocd
spec:
  goTemplate: true                 # 必须加！新版 ArgoCD 默认关闭旧模板语法
  generators:
    - scmProvider:
        github:
          organization: qianxue-world
          api: "https://api.github.com/"
          tokenRef:
            secretName: github-token
            key: token
          allBranches: true
        filters:
          - repositoryMatch: "lovetest-*"
  template:
    metadata:
      name: '{{.repository.name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/qianxue-world/{{.repository.name}}.git'
        targetRevision: HEAD
        path: k8s/
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: '{{.repository.name}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
        syncWindow: "*/3 * * * *"